client_list: use memcpy instead of strncpy for fixed size mutable_key
Fixes:
  error: 'char* strncpy(char*, const char*, size_t)' specified bound 2
         equals destination size [-Werror=stringop-truncation]