bazel: enable aligned new allocation feature of compiler
Fixes:
  error: 'new' of type 'torrent::HashQueue' with extended alignment 128 [-Werror=aligned-new=]

Caused by: lt_cacheline_aligned